#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_PATH="${PROJECT_DIR}/$(basename -- "${BASH_SOURCE[0]}")"
SERVICE_NAME="wmadapter.service"
SERVICE_DIR="${WMADAPTER_SYSTEMD_DIR:-/etc/systemd/system}"
SERVICE_FILE="${SERVICE_DIR}/${SERVICE_NAME}"
BIN_DIR="${WMADAPTER_BIN_DIR:-/usr/local/bin}"
CLI_FILE="${BIN_DIR}/wmadapter"
if [[ $EUID -ne 0 ]]; then
  if ! command -v sudo >/dev/null 2>&1; then
    echo "This uninstaller needs root privileges, but sudo is not installed. Run it as root." >&2
    exit 1
  fi
  ORIGINAL_HOME="$HOME"
  echo "Root privileges are required to remove the system-wide service; requesting them once..."
  exec sudo env WMADAPTER_UNINSTALL_HOME="$ORIGINAL_HOME" "$SCRIPT_PATH" "$@"
fi

PROFILE_ROOT="${WMADAPTER_PROFILE_ROOT:-${WMADAPTER_UNINSTALL_HOME:-$HOME}/.local/share/wmadapter/profiles}"
UNINSTALL_TIMEOUT_SEC="${UNINSTALL_TIMEOUT_SEC:-10}"

if [[ ! "$UNINSTALL_TIMEOUT_SEC" =~ ^[1-9][0-9]*$ ]]; then
  echo "Warning: invalid UNINSTALL_TIMEOUT_SEC='$UNINSTALL_TIMEOUT_SEC'; using 10 seconds." >&2
  UNINSTALL_TIMEOUT_SEC=10
fi

run_bounded() {
  local label="$1"
  shift
  if ! command -v setsid >/dev/null 2>&1; then
    echo "Warning: $label skipped: setsid command is missing." >&2
    return 127
  fi
  local marker
  marker="$(mktemp)"
  local status=0
  setsid "$@" &
  local command_pid=$!
  (
    sleep "$UNINSTALL_TIMEOUT_SEC"
    printf 'timeout' >"$marker"
    kill -TERM -- "-$command_pid" 2>/dev/null || true
    sleep 1
    kill -KILL -- "-$command_pid" 2>/dev/null || true
  ) &
  local watchdog_pid=$!
  wait "$command_pid" || status=$?
  kill "$watchdog_pid" 2>/dev/null || true
  wait "$watchdog_pid" 2>/dev/null || true
  if [[ -s "$marker" ]]; then
    status=124
  fi
  rm -f -- "$marker"
  case "$status" in
    0) echo "OK: $label" ;;
    124|137) echo "Warning: $label timed out after ${UNINSTALL_TIMEOUT_SEC}s; continuing." >&2 ;;
    127) echo "Warning: $label failed: command is missing." >&2 ;;
    *) echo "Warning: $label failed (exit $status); continuing." >&2 ;;
  esac
  return "$status"
}

echo "Uninstalling Web Model Adapter local service..."
if command -v systemctl >/dev/null 2>&1; then
  if [[ $EUID -eq 0 ]]; then
    run_bounded "systemd service stop/disable" systemctl disable --now "$SERVICE_NAME" || true
    run_bounded "systemd daemon-reload" systemctl daemon-reload || true
  else
    echo "Warning: run uninstall.sh as root to remove the system service." >&2
  fi
else
  echo "Warning: systemctl command is missing; service control skipped." >&2
fi

# Remove only the exact unit generated by install.sh after the bounded stop.
rm -f -- "$SERVICE_FILE"
if [[ -f "$CLI_FILE" ]] && grep -q "WMADAPTER_INSTALL_MARKER" "$CLI_FILE"; then
  rm -f -- "$CLI_FILE"
fi

# Keep local cleanup safe and idempotent: every target is rooted at this script
# or is an explicitly configured generated unit path. Profile removal is
# intentional: reinstalling must require a fresh provider login.
rm -rf -- "$PROJECT_DIR/.venv" "$PROJECT_DIR/.wmadapter-profile"
rm -rf -- "$PROFILE_ROOT"
rm -f -- \
  "$PROJECT_DIR/.env" \
  "$PROJECT_DIR/config.yaml" \
  "$PROJECT_DIR/.wmadapter.pid" \
  "$PROJECT_DIR/wmadapter.install.log" \
  "$PROJECT_DIR/wmadapter.log"
rm -f -- "${WMADAPTER_UNINSTALL_HOME:-$HOME}/.local/share/wmadapter/wmadapter.log"

echo "Web Model Adapter local cleanup completed. Source files were kept in: $PROJECT_DIR"
