import { createOpenAICompatible } from '@ai-sdk/openai-compatible';
import { generateText, streamText, tool, jsonSchema } from 'ai';
import assert from 'node:assert/strict';
const baseURL=process.env.WEBBRIDGE_TEST_URL || 'http://127.0.0.1:18761/v1';
const provider=createOpenAICompatible({name:'webbridge',baseURL,apiKey:'fixture'});
const model=provider('deepseek-chat');
const tools={lookup:tool({description:'Lookup',inputSchema:jsonSchema({type:'object',properties:{}})})};
const result=await generateText({model,prompt:'value?',tools});
assert.equal(result.finishReason,'tool-calls');
const call=result.toolCalls[0];
const messages=[{role:'user',content:'value?'},...result.response.messages,{role:'tool',content:[{type:'tool-result',toolCallId:call.toolCallId,toolName:'lookup',output:{type:'text',value:'42'}}]}];
assert.equal((await generateText({model,messages,tools})).text,'42');
const streaming=streamText({model,prompt:'hi'});
assert.equal(await streaming.text,'hello');
console.log('OpenCode documented AI SDK transport: text/tool/result/SSE PASS');
if (!process.env.OPENCLAW_AI_DIR) throw new Error('Set OPENCLAW_AI_DIR to installed @openclaw/ai/dist');
const { pathToFileURL } = await import('node:url');
const { createLlmRuntime, createApiRegistry } = await import(pathToFileURL(process.env.OPENCLAW_AI_DIR + '/index.mjs'));
const { registerBuiltInApiProviders } = await import(pathToFileURL(process.env.OPENCLAW_AI_DIR + '/providers.mjs'));
const registry=createApiRegistry();registerBuiltInApiProviders(registry);
const runtime=createLlmRuntime(registry);
const ocModel={id:'deepseek-chat',name:'Fixture',api:'openai-completions',provider:'webbridge',baseUrl:baseURL,reasoning:false,input:['text'],contextWindow:8192,maxTokens:1024,cost:{input:0,output:0,cacheRead:0,cacheWrite:0}};
const context={messages:[{role:'user',content:'value?',timestamp:Date.now()}],tools:[{name:'lookup',description:'Lookup',parameters:{type:'object',properties:{}}}]};
const answer=await runtime.completeSimple(ocModel,context,{apiKey:'fixture'});
assert.equal(answer.stopReason,'toolUse',JSON.stringify(answer));
const ocCall=answer.content.find(x=>x.type==='toolCall');
context.messages.push(answer,{role:'toolResult',toolCallId:ocCall.id,toolName:'lookup',content:[{type:'text',text:'42'}],isError:false,timestamp:Date.now()});
const final=await runtime.completeSimple(ocModel,context,{apiKey:'fixture'});
assert.equal(final.stopReason,'stop',JSON.stringify(final));
assert.equal(final.content.find(x=>x.type==='text').text,'42');
console.log('Installed OpenClaw AI transport: streamed tool/result PASS');
